import './Admin_pages/LoginPage'
import './Admin_pages/LandingPage'
import './Admin_pages/BusinessPage'
import './Admin_pages/BrandPage'
import './Admin_pages/LocationPage'
import './Admin_pages/UserPage'
import './Admin_pages/MenuPage'
import 'cypress-file-upload';
import '@faker-js/faker'
import 'cypress-wait-until';
import './Admin_pages/Campaign_Manager/Campaign_page'
import 'xpath_cypress';
import "allure-cypress";